<a href="https://colab.research.google.com/github/vikrantyadav11234/PyTorch_Practice/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    # self.linear = nn.Linear(input, output)
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn. Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [4]:
# Create Dataset
features = torch.rand(10,5)
# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5948],
        [0.5843],
        [0.5465],
        [0.4994],
        [0.5575],
        [0.5585],
        [0.5759],
        [0.4978],
        [0.5039],
        [0.5207]], grad_fn=<SigmoidBackward0>)

In [5]:
# Show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1778,  0.0312, -0.4038,  0.1139,  0.2728]], requires_grad=True)

In [6]:
# Show bias
model.linear.bias

Parameter containing:
tensor([0.1012], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Create a nn with a hiddel layer

- input layer - 5 inputs
- hidden layer - 3 neurons
- out - 1 neuron

- total parameters - 18 weights , 4 bias
- in hidden layer -use relu
- in output layer - use sigmoid


In [11]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    # self.linear = nn.Linear(input, output)
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [12]:
# Create Dataset
features = torch.rand(10,5)
# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4325],
        [0.4115],
        [0.4381],
        [0.4110],
        [0.4356],
        [0.4162],
        [0.4324],
        [0.4331],
        [0.4149],
        [0.4283]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3249, -0.3037,  0.4148, -0.1532, -0.3316],
        [ 0.2827,  0.3740,  0.3776,  0.3478,  0.2319],
        [ 0.1062, -0.3794, -0.2899, -0.1294,  0.2891]], requires_grad=True)

In [14]:
model.linear2.weight

Parameter containing:
tensor([[-0.2434, -0.1016, -0.0550]], requires_grad=True)

In [15]:
model.linear1.bias

Parameter containing:
tensor([0.1955, 0.0475, 0.2247], requires_grad=True)

In [16]:
model.linear2.bias

Parameter containing:
tensor([-0.1337], requires_grad=True)

In [17]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Sequential Containers

In [18]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

## Case study

In [19]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [21]:
df.shape

(569, 33)

In [22]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [23]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [25]:
# scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [27]:
# numpy array to tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [28]:
X_train_tensor.shape

torch.Size([455, 30])

In [29]:
y_train_tensor.shape

torch.Size([455])

In [30]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [31]:
learning_rate = 0.1
epochs = 25

In [35]:
X_train_tensor.dtype

torch.float64

In [37]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.type(torch.float32))

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7669162750244141
Epoch: 2, Loss: 0.748889148235321
Epoch: 3, Loss: 0.7367170453071594
Epoch: 4, Loss: 0.7281798124313354
Epoch: 5, Loss: 0.7218232154846191
Epoch: 6, Loss: 0.7167733311653137
Epoch: 7, Loss: 0.7125326991081238
Epoch: 8, Loss: 0.708823561668396
Epoch: 9, Loss: 0.705490231513977
Epoch: 10, Loss: 0.7024422883987427
Epoch: 11, Loss: 0.6996243000030518
Epoch: 12, Loss: 0.6969998478889465
Epoch: 13, Loss: 0.6945436000823975
Epoch: 14, Loss: 0.692236602306366
Epoch: 15, Loss: 0.6900643110275269
Epoch: 16, Loss: 0.6880145072937012
Epoch: 17, Loss: 0.6860774159431458
Epoch: 18, Loss: 0.6842446327209473
Epoch: 19, Loss: 0.6825088262557983
Epoch: 20, Loss: 0.6808634996414185
Epoch: 21, Loss: 0.6793030500411987
Epoch: 22, Loss: 0.6778222918510437
Epoch: 23, Loss: 0.6764165163040161
Epoch: 24, Loss: 0.6750814318656921
Epoch: 25, Loss: 0.6738131046295166


In [39]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.type(torch.float32))
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5350877046585083


## use built-in loss function and optimizer

In [40]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


In [41]:
learning_rate = 0.1
epochs = 25

In [42]:
loss_function = nn.BCELoss()


In [ ]:
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [48]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.type(torch.float32))

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.type(torch.float32).view(-1,1))

  # clear gradients
  optimizer.zero_grad()
  # backword pass
  loss.backward()

  # parameters update
  optimizer.step()
  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.908372163772583
Epoch: 2, Loss: 0.6384310722351074
Epoch: 3, Loss: 0.5001511573791504
Epoch: 4, Loss: 0.4214939475059509
Epoch: 5, Loss: 0.37050506472587585
Epoch: 6, Loss: 0.33433592319488525
Epoch: 7, Loss: 0.30705952644348145
Epoch: 8, Loss: 0.2855737805366516
Epoch: 9, Loss: 0.2680932581424713
Epoch: 10, Loss: 0.25351399183273315
Epoch: 11, Loss: 0.24111413955688477
Epoch: 12, Loss: 0.2304001748561859
Epoch: 13, Loss: 0.22102224826812744
Epoch: 14, Loss: 0.21272465586662292
Epoch: 15, Loss: 0.20531579852104187
Epoch: 16, Loss: 0.19864870607852936
Epoch: 17, Loss: 0.19260874390602112
Epoch: 18, Loss: 0.18710482120513916
Epoch: 19, Loss: 0.18206347525119781
Epoch: 20, Loss: 0.1774248331785202
Epoch: 21, Loss: 0.17313934862613678
Epoch: 22, Loss: 0.16916565597057343
Epoch: 23, Loss: 0.16546890139579773
Epoch: 24, Loss: 0.1620195358991623
Epoch: 25, Loss: 0.15879206359386444


In [49]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.type(torch.float32))
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5209295153617859
