<a href="https://colab.research.google.com/github/vikrantyadav11234/PyTorch_Practice/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [ ]:
# using empty
a= torch.empty(2,3) #no new values will be asigned

In [ ]:
type(a)

torch.Tensor

In [ ]:
# using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.3393, 0.0303, 0.3590],
        [0.9707, 0.4238, 0.5022]])

In [ ]:
# using of seed- randumly but the output of rand same each time- reproducability
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor- custome tensor
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [ ]:
#other ways

#arange
print("using arange---", torch.arange(0,10))

# using linespace
print("using linespace---", torch.linspace(0,10,10))

# using eye
print("using eye", torch.eye(5))

# using full
print("using full", torch.full((3,3),5))

using arange--- tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linespace--- tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
#arange
print("using arange---", torch.arange(0,10,2))

using arange--- tensor([0, 2, 4, 6, 8])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
# make same shape tensor using empty function
torch.empty_like(x)

tensor([[    138903657045392,           144325520,                   0],
        [                  0,        197568495616, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)  # it will not work because rand function generates floats between 0 and 1.

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Data type

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

### Scalar operations

In [ ]:
x=torch.rand(2,2)

In [ ]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
# substitution
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
# multiplication
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
# Division
x/2

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [ ]:
#Integer division
(x*100)/3

tensor([[23.7255, 26.2527],
        [13.9435, 30.0472]])

In [ ]:
((x*100)/3)%2

tensor([[1.7255, 0.2527],
        [1.9435, 0.0472]])

In [ ]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### Element wise operations

In [ ]:
a = torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# add
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
# subtraction
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
# multiplication
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
#Division
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
# power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [ ]:
# mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.2,2.3,3.4,4.5])

In [ ]:
# round
torch.round(d)

tensor([1., 2., 3., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operations

In [ ]:
e = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15,  9])

In [ ]:
# mean
torch.mean(e)
# mean along columns
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
## max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [ ]:
# varience
torch.var(e)

tensor(9.8667)

In [ ]:
# argmax
torch.argmax(e)

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(5)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=2, high=19)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[11,  5],
        [11, 17],
        [15,  5]])


In [ ]:
## Matrix multiplication
torch.matmul(f,g)

tensor([[207, 169],
        [303, 233]])

In [ ]:
vector1= torch.tensor([1,2])
vector2 = torch.tensor([2,3])

# dot product
torch.dot(vector1,vector2)

tensor(8)

In [ ]:
# transpose
f

tensor([[5, 7, 5],
        [9, 9, 7]])

In [ ]:
torch.transpose(f, 0,1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=1, high=20, dtype= torch.float32)
h

tensor([[ 5., 16.,  5.],
        [12., 14., 12.],
        [ 6., 16., 16.]])

In [ ]:
# determinant
torch.det(h)

tensor(-1220.)

In [ ]:
#inverse
torch.inverse(h)

tensor([[-2.6230e-02,  1.4426e-01, -1.0000e-01],
        [ 9.8361e-02, -4.0984e-02,  4.6566e-10],
        [-8.8525e-02, -1.3115e-02,  1.0000e-01]])

### 5. comparision operations

In [ ]:
i= torch.randint(size=(3,4), low=1, high=34)
j= torch.randint(size=(3,4), low= 3, high = 35, dtype = torch.float32)

print(i)
print(j)

tensor([[13, 16, 10, 31],
        [33,  6, 22,  9],
        [16, 27, 11, 11]])
tensor([[13.,  6.,  9.,  6.],
        [23., 18., 13., 26.],
        [25., 18., 31.,  6.]])


In [ ]:
# greater then
i > j

tensor([[ True, False, False, False],
        [False,  True,  True,  True],
        [False, False,  True, False]])

In [ ]:
# less then
i<j

tensor([[False,  True, False,  True],
        [ True, False, False, False],
        [ True,  True, False,  True]])

In [ ]:
# equal to
i=j

In [ ]:
# not equal to
i!=j

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# log
torch.log(j)

tensor([[1.0986, 3.2958, 1.6094, 3.1781],
        [2.5649, 2.9957, 2.3979, 2.7726],
        [2.5649, 3.4965, 2.9957, 3.1781]])

In [ ]:
# exponents
torch.exp(j)

tensor([[2.0086e+01, 5.3205e+11, 1.4841e+02, 2.6489e+10],
        [4.4241e+05, 4.8517e+08, 5.9874e+04, 8.8861e+06],
        [4.4241e+05, 2.1464e+14, 4.8517e+08, 2.6489e+10]])

In [ ]:
# square root
torch.sqrt(j)

tensor([[1.7321, 5.1962, 2.2361, 4.8990],
        [3.6056, 4.4721, 3.3166, 4.0000],
        [3.6056, 5.7446, 4.4721, 4.8990]])

In [ ]:
# sigmoid
torch.sigmoid(j)

tensor([[0.9526, 1.0000, 0.9933, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [ ]:
# softmax
torch.softmax(j, dim=0)

tensor([[5.4118e-06, 3.0721e-06, 2.7895e-10, 2.0612e-09],
        [1.1920e-01, 5.0000e-01, 1.5230e-08, 1.0000e+00],
        [8.8079e-01, 5.0000e-01, 1.0000e+00, 2.0612e-09]])

In [ ]:
# relu
torch.relu(j)

tensor([[13.,  6.,  9.,  6.],
        [23., 18., 13., 26.],
        [25., 18., 31.,  6.]])

### Inplace operations

In [ ]:
m = torch.rand(2,3)
n= torch.rand(2,3)

print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])


In [ ]:
m =m +n

In [ ]:
m.add_(n)

tensor([[2.4817, 1.0582, 2.3761],
        [1.3696, 1.2339, 1.4910]])

In [ ]:
m

tensor([[2.4817, 1.0582, 2.3761],
        [1.3696, 1.2339, 1.4910]])

In [ ]:
torch.relu(m)

tensor([[2.4817, 1.0582, 2.3761],
        [1.3696, 1.2339, 1.4910]])

In [ ]:
m.relu_()

tensor([[2.4817, 1.0582, 2.3761],
        [1.3696, 1.2339, 1.4910]])

In [ ]:
m

tensor([[2.4817, 1.0582, 2.3761],
        [1.3696, 1.2339, 1.4910]])

## Copying a tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
a[0][0]= 0

In [ ]:
a

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
id(a)

138899178999824

In [ ]:
id(b)

138899178999824

In [ ]:
 b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
a[0][1]=10

In [ ]:
a

tensor([[ 0.0000, 10.0000,  0.6688],
        [ 0.2651,  0.2336,  0.5057]])

In [ ]:
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
id(a)

138899178999824

In [ ]:
id(b)

138899178791056

## Tensor operations on gpu

In [ ]:
torch.cuda.is_available()

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.1192, 0.4828, 0.9105],
        [0.4266, 0.4203, 0.2719]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.0064, 0.4451, 0.1580],
        [0.8119, 0.4629, 0.3227]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[     134842408414608,       96429401449888,     3503044046096754],
        [-2738188572259385344,  7020378893157883663,  8389754676633367105]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4076, 0.6037, 0.9820],
        [0.0117, 0.3891, 0.5056]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9594, 0.1334],
        [0.8591, 0.6639]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9205, 0.0178],
        [0.7380, 0.4408]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0554, 0.7498, 0.3761],
        [0.6721, 0.5572, 0.2686]])
tensor([[0.3466, 0.1875, 0.7433],
        [0.6713, 0.9844, 0.0096]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0554, 0.1872, 0.3761],
        [0.0008, 0.5572, 0.0091]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 2., 9.],
        [7., 6., 5.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18, 13])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 4., 7.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
# product
torch.prod(e)

tensor(3780.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [ ]:
# variance
torch.var(e)

tensor(9.2000)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 7, 8],
        [7, 9, 9]])
tensor([[1, 1],
        [4, 2],
        [4, 7]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[63, 73],
        [79, 88]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 7],
        [7, 9],
        [8, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 2., 2.],
        [4., 8., 8.],
        [5., 0., 4.]])

In [ ]:
# determinant
torch.det(h)

tensor(224.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.1429, -0.0357,  0.0000],
        [ 0.1071,  0.0982, -0.2500],
        [-0.1786,  0.0446,  0.2500]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 1],
        [1, 1, 3]])
tensor([[2, 6, 3],
        [5, 2, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 6., 4.],
        [4., 8., 6.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 0.0000],
        [1.9459, 0.0000, 2.0794]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 5.4598e+01, 2.7183e+00],
        [1.0966e+03, 2.7183e+00, 2.9810e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 1.0000],
        [2.6458, 1.0000, 2.8284]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.7311],
        [0.9991, 0.7311, 0.9997]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.1192, 0.1192],
        [0.9820, 0.8808, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[0., 6., 4.],
        [4., 8., 6.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2018, 0.1089, 0.7653],
        [0.6473, 0.3401, 0.6406]])
tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])


In [ ]:
m.add_(n)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
n

tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])

In [ ]:
torch.relu(m)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m.relu_()

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838567488544

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838569581552

# Tensor operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3322, 0.1477, 0.8894],
        [0.9264, 0.4043, 0.9747]], device='cuda:0')

In [ ]:
# moving an existing tensor to gpu
a = torch.rand(2,3)
a

tensor([[0.1860, 0.2450, 0.1151],
        [0.7211, 0.2074, 0.0435]])

In [ ]:
b = a.to(device)

In [ ]:
b+5

tensor([[5.1860, 5.2450, 5.1151],
        [5.7211, 5.2074, 5.0435]], device='cuda:0')

## Reshaping tensors

In [ ]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b= torch.rand(2,3,4)
b

tensor([[[0.2943, 0.3591, 0.6933, 0.7879],
         [0.9664, 0.8589, 0.3979, 0.2232],
         [0.7821, 0.7403, 0.9563, 0.0341]],

        [[0.8104, 0.2460, 0.0137, 0.5446],
         [0.6974, 0.5170, 0.9781, 0.4756],
         [0.9214, 0.6385, 0.9766, 0.8312]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze - add new tensor in given position
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
## Squeez
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])

In [ ]:
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])